### ISSUE TITLE
Octal literal in strict mode (3:29)

### ISSUE THREAD

**Issue by jarnovanrhijn** [swanky-docs/swanky#14]
First of, thanks for open sourcing this great product.

I've tried to run swanky locally on my windows machine. however i'm getting an error which i can't seem to fix.

`ERROR in ./~/swanky/src/loaders/bootstrap-loader?src=C:/project/3.0 Dev/snippets!./~/swanky/src/loaders/bootstrap-loader/bootstrap-loader-template.js
Module parse failed: C:\project\3.0 Dev\node_modules\swanky\src\loaders\bootstrap-loader\index.js?src=C:\project\3.0 Dev\Source\snippets!C:\project\3.0 Dev\node_modules\swanky\src\loaders\bootstrap-loader\bootstrap-loader-template.js **Octal literal in strict mode (3:29)**
**You may need an appropriate loader to handle this file type.**
| 'use strict' 
| module.exports = (function() {
|     **require('C:\project\3.0 Dev\Source\snippets\colour-drop\index.js');**
|   })();`

I'm thinking it has something to do with the directory name including numbers but i'm not sure.

**Comment by rodleviton** [comment]
Hi @jarnovanrhijn, apologies as I have not yet done any testing on Windows based systems (just unix at the moment). Give me a few days and I will try and get a build running on a Windows system.

**Comment by jarnovanrhijn** [comment]
Hi Rod,

Thanks for the quick reply! i think it has something to do with windows using front slashes instead of back slashes. (http://stackoverflow.com/questions/34329149/nodejs-absolute-paths-in-windows-with-forward-slash)

**Comment by rodleviton** [comment]
Closing as Swanky is now building on Windows systems.
