### ISSUE TITLE
use ng-template with templateUrl

### ISSUE THREAD

**Issue by jarnovanrhijn** [swanky-docs/swanky#16]
Is it possible to have an angular directive which uses templateUrl and render it with ngDocs?

**Comment by rodleviton** [comment]
@jarnovanrhijn not sure what you are asking here. NgDocs provides an `@example` attribute that allows you to specify an example in your comments. To make it work within Swanky you would need to wire up the angular app to load the correct code. The [Swanky Docs Patterns](https://github.com/swanky-docs/patterns.swanky-docs.org/blob/master/swanky.config.yaml#L23) example has a few good examples for you to look at.

**Comment by jarnovanrhijn** [comment]
Ahh allright, i see it in the examples!!
