### ISSUE TITLE
Install command - To devDependencies or dependencies ?

### ISSUE THREAD

**Issue by BobbyBabes** [swanky-docs/swanky#17]
npm install swanky --save-dev
as per https://raw.githubusercontent.com/swanky-docs/swanky/master/README.md
or :
npm install swanky --save
as per https://guide.swanky-docs.org/getting-started/setup-installation.html

**Comment by rodleviton** [comment]
Hi @BobbyBabes `swanky` should be saved as a `devDependency` as it is only need to generate the static files at build time. Thanks for picking up this mistake. I will update the guide.

**Comment by BobbyBabes** [comment]
No, thank you for Swanky. It might actually turn creating docs into an enjoyable task.
