### ISSUE TITLE
[REQUEST] Add responsive view toggle

### ISSUE THREAD

**Issue by dlewand691** [swanky-docs/swanky#32]
Would be awesome to have the ability to resize the viewport to preview at various widths. Similar to this styleguide from Huge: http://hugeinc.github.io/styleguide/demo/index.html

**Comment by rodleviton** [comment]
Agreed. This is a feature I would like to implement without the `<iframe>` tag as per most implementations. Also as this is a theme level feature I will be moving this issue to the default [swanky-theme](https://github.com/swanky-docs/swanky-theme).
