### ISSUE TITLE
Snippet styles not included

### ISSUE THREAD

**Issue by mattkibbler** [swanky-docs/swanky#36]
Hi!

When I create snippets using the structure set out in the Swanky Docs the snippet HTML and JS are included in the site just fine, but the CSS that I put in the snippet's `style.styl` file does not get included.

I can't see where this should be happening within the Swanky core files. Can anybody please point me in the right direction? Am I missing something?

**Comment by mattkibbler** [comment]
Maybe it would help to specify how I expect/would like this to work...

Ultimately I would be using Swanky Docs to create a pattern library for a client who would receive a single compiled CSS and JS file, so they could browse the patterns and see the markup that they will need to copy and paste into place.

I like the approach of scoping all of the Swanky class names to avoid collisions with the real pattern library CSS, but how am I to create the separate deliverable CSS and JS files within Swanky? Could the system process all of the `.styl` files from the `snippets` directory and compile them together into a single CSS file? Or should I be processing and compiling this CSS myself and drop it into the pattern library somehow?

It may be that all this functionality is already built into Swanky Docs, but I simply haven't found it.

**Comment by rodleviton** [comment]
Here is a simple example of how the stylus file is imported into the snippet:

https://github.com/swanky-docs/guide.swanky-docs.org/blob/master/src/snippets/colour-drop/index.js#L1

Ultimately it is just a matter of importing the stylus file into the snippet `index.js`.

`import './style.styl'`

**Comment by rodleviton** [comment]
@mattkibbler as for question number 2. Swanky was not really intended to produce production ready outputs for components etc. It is more intended to import and showcase your components and css assets -> generally built in your own app/project as this will give you the most control.

**Comment by mattkibbler** [comment]
@rodleviton Ok, that makes sense. In that case, is it possible to add some way of easily including pre-compiled CSS/JS files, maybe via the config? These files would then be copied across into the `docs` folder and referenced in the theme.

**Comment by rodleviton** [comment]
There are many ways to do this. My preference is to import your production assets into the project via your `package.json` (most probably from github). That way you can always be referencing the 'real' source of your application. e.g.
